name: Codespell

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Fails the job by default when misspellings are found
      - name: Run codespell
        uses: codespell-project/actions-codespell@v2

