name: Flutter CI

on:
  push:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'assets/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'android/**'
      - 'ios/**'
      - '.github/workflows/flutter-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'assets/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'android/**'
      - 'ios/**'
      - '.github/workflows/flutter-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Detect whether app-relevant files changed
      - name: Filter changed paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            app:
              - 'lib/**'
              - 'test/**'
              - 'assets/**'
              - 'pubspec.yaml'
              - 'pubspec.lock'
              - 'android/**'
              - 'ios/**'

      # Stop immediately if nothing relevant changed
      - name: No app changes — skip
        if: steps.changes.outputs.app != 'true'
        run: |
          echo "No app code changes detected. Skipping build."
          exit 0

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'
          cache: true

      # Optional but helps Gradle incremental builds
      - name: Enable Gradle build cache
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.caching=true" >> ~/.gradle/gradle.properties

      # Restore caches including previous build outputs
      - name: Restore build & tool caches
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            build
          key: ${{ runner.os }}-flutter-3.35.1-java21-${{ hashFiles('pubspec.lock', 'lib/**', 'android/**', 'ios/**') }}
          restore-keys: |
            ${{ runner.os }}-flutter-3.35.1-java21-

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      # Only build if we didn't restore build outputs from cache
      - name: Build APK
        if: steps.cache.outputs.cache-hit != 'true'
        run: flutter build apk --release

      - name: Build App Bundle
        if: steps.cache.outputs.cache-hit != 'true'
        run: flutter build appbundle --release

      # Upload from build/ whether it came from cache or a fresh build
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-builds
          path: |
            build/app/outputs/**/*.apk
            build/app/outputs/**/*.aab

